### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by timscriptov** [itsvks19/LayoutEditor#23]
Hi, Do you plan to release the project as a separate library? So that you can pass the path to the layout through the bundle

**Comment by itsvks19** [comment]
@TimScriptov I don't understand what do my mean. Can you explain in detail?

**Comment by TimScriptov** [comment]
Split the project into two modules.

The app module contains a code editor.  And the launch of the Graphic Designer.

The second module is library, which contains the code for the graphic designer.

And it turns out that other developers will be able to use your graphic designer without any problems.


**Example:**
_app module:_
val intent = Intent(...)
intent.putString("path", path)
startActivity(intent)

_library module:_
...onCreate(...) {
val path = intent.getString("path")
showUIDesigner(path)

**Comment by TimScriptov** [comment]
My example:
https://github.com/TimScriptov/App-UI-Designer/blob/main/app/src/main/java/com/mcal/example/MainActivity.kt

It Aide UI Designer

**Comment by itsvks19** [comment]
Thanks

**Comment by itsvks19** [comment]
I will not release this project as a separate library.
